on:
  workflow_dispatch:
jobs:
  print_congratulations:
    runs-on: ubuntu-latest
    steps:
    - name: congrats
      run: |
        cat << "EOF"
                                         _       
                                        | |      
          ___ ___  _ __   __ _ _ __ __ _| |_ ___ 
         / __/ _ \| '_ \ / _` | '__/ _` | __/ __|
        | (_| (_) | | | | (_| | | | (_| | |_\__ \
         \___\___/|_| |_|\__, |_|  \__,_|\__|___/
                          __/ |                  
                         |___/ 
        EOF
        # https://ascii.co.uk/art/congrats
