on:
  workflow_dispatch:
jobs:
  print_congratulations:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '                                 _       '
        echo '                                | |      '
        echo '  ___ ___  _ __   __ _ _ __ __ _| |_ ___ '
        echo ' / __/ _ \| '_ \ / _` | '__/ _` | __/ __|'
        echo '| (_| (_) | | | | (_| | | | (_| | |_\__ \'
        echo ' \___\___/|_| |_|\__, |_|  \__,_|\__|___/'
        echo '                  __/ |                  '
        echo '                 |___/                   '
        # https://ascii.co.uk/art/congrats
