on:
  repository_dispatch:
    types: [test_completed]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: "So sad. Better luck next time!"
        run: echo $MESSAGE
        
  run_if_success:
    if: ${{ github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        

        run: echo $MESSAGE

      - uses: ./.github/workflows/congratulations.yml
